In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# import the dataset
dataset = pd.read_csv('../Data/mapped-table (1).csv')
dataset.head()

,No of people,Household Consumption [kWh/year],EV distance [KM/year],PV [kWp],Battery [kWh],Have heatpump? [y = 1 n = 0],Have Heating Rod? [y = 1 n = 0],Heatpump Consumption [kWh/year],heatPumpRequirement [kWh],heatingRodRequirment [kWh],...,heatingRodThroughPV [kWh],heatpumpThroughBattery [kWh],Index in the table,calculated_ev_consumption [kWh],total power requirements [kWh],pv_power_generation [kWh],consumption_through_pv [kWh],adjusted_battery_consumption [kWh],consumption_through_battery [kWh],grid_feed_in [kWh]
0,2,2000,0,5,4,0,0,0,0,0,...,0,0,0,0.0,2000,4998.044337,725,0.0,0,4273.044337
1,2,2000,0,5,4,0,1,3000,0,1192,...,1192,0,2,0.0,3192,4998.044337,1917,0.0,0,3081.044337
2,2,2000,0,5,4,0,1,6000,0,1192,...,1192,0,18,0.0,3192,4998.044337,1917,0.0,0,3081.044337
3,2,2000,0,5,4,0,1,9000,0,1192,...,1192,0,34,0.0,3192,4998.044337,1917,0.0,0,3081.044337
4,2,2000,0,5,4,1,0,3000,1731,0,...,0,0,1,0.0,3731,4998.044337,1665,0.0,0,3333.044337